stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'
          - script: |
                npm install -g @angular/cli
                npm install
                ng build --prod
            displayName: 'npm install and build'
      - job: publish
        steps:
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: dist'
            inputs:
              PathtoPublish: 'dist/my-pipeline'

