stages:
  - stage: deploy
    dependsOn:
    - build
    jobs:
      - job: deployment
        steps:
          - task: AzureStaticWebApp@0
            inputs:
              output_location: $(Build.ArtifactStagingDirectory)
              azure_static_web_apps_api_token: $(deployment_token)
            displayName: 'Deploy'






